import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import "./globals.css";
import "./ui/material3-tokens/dark.css";
import "./ui/material3-tokens/light.css";
import ThemeProvider from "./lib/contexts/themeContext";
import App from "./ui/App";
import localFont from "next/font/local";
import MUICustomThemeProvider from "./lib/contexts/MuiThemeContext";
import "animate.css";
import dbConnect from "./lib/connectDatabase";
// import dynamic from "next/dynamic";
// const NoSSRTokenProvider = dynamic(() => import("./lib/contexts/tokenContext"), { ssr: false });
require("@/app/lib/connectDatabase");
// setup mongoose models
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const GoogleSans = localFont({
  src: "../public/assets/fonts/GoogleSans-Regular.ttf",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en" className="light">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            try{
              const userTheme = localStorage.getItem('theme');
              document.documentElement.classList.remove('dark');
              document.documentElement.classList.remove('light');
              if (userTheme) {
                document.documentElement.classList.add(userTheme);
                } else {
                  document.documentElement.classList.add('light');
              }
                if (userTheme) {
                document.documentElement.setAttribute("data-mui-color-scheme" ,userTheme);
                } else {
                  document.documentElement.setAttribute("data-mui-color-scheme",'light');
              }
              }catch (err){console.log(err)}
              `,
          }}
        />
      </head>
      <body className={`${GoogleSans.className}`}>
        <AppRouterCacheProvider>
          <MUICustomThemeProvider>
            <ThemeProvider>
              <App>{children}</App>
            </ThemeProvider>
          </MUICustomThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
